### ISSUE TITLE
Link zum Datenschutz im Ipressum funktioniert nicht

### ISSUE THREAD

**Issue by mccrossen** [oprvc/oprvc.github.io#21]
Hallo,
der Link zu 'https://opr.vc/privacy' im Impressum funktioniert nicht.
Ich gehe davon aus, das die korrekte Seite diese wäre: https://opr.vc/datenschutzerklaerung/

**Comment by sebastianhofmannlegal** [comment]
Vielen Dank. Ich habe es soeben angepasst. Schönen Tag noch.
